# -*- coding: utf-8 -*-
"""MultiAgent_LoanPredictionSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nFGMSJGnePD6CxEUFYV0oBye2Y6ETn0

############################################
# Cell 1 — Setup & installs (run once)
############################################
"""

############################################
# Cell 1 — Setup & installs (run once)
############################################
# If you run in a fresh environment, run these installs (uncomment to run)
!pip install pandas scikit-learn imbalanced-learn shap matplotlib seaborn jinja2 weasyprint joblib beautifulsoup4 requests pyyaml crewai crewai-tools

"""############################################
# Cell 2 — Imports
############################################
"""

import json
from datetime import datetime
import pandas as pd
import numpy as np
import joblib
import yaml
import os

# ML
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, average_precision_score, classification_report, confusion_matrix

# Explainability
import shap
import matplotlib.pyplot as plt
import seaborn as sns

# Reporting
from jinja2 import Environment, FileSystemLoader

# CrewAI (optional in CrewAI environment)
try:
  from crewai import Agent, Task, Crew
  from crewai_tools import SerperDevTool, ScrapeWebsiteTool, FileReadTool
  CREWAI_AVAILABLE = True
except Exception:
  CREWAI_AVAILABLE = False

"""############################################
# Cell 3 — Paths and folders
############################################
"""

PROJECT_ROOT = '/content/drive/MyDrive/Colab Notebooks/MultiAgent_Loan'
os.makedirs(os.path.join(PROJECT_ROOT,'config'), exist_ok=True)
os.makedirs(os.path.join(PROJECT_ROOT,'data','raw'), exist_ok=True)
os.makedirs(os.path.join(PROJECT_ROOT,'data','processed'), exist_ok=True)
os.makedirs(os.path.join(PROJECT_ROOT,'models'), exist_ok=True)
os.makedirs(os.path.join(PROJECT_ROOT,'artifacts'), exist_ok=True)
os.makedirs(os.path.join(PROJECT_ROOT,'reports'), exist_ok=True)

"""############################################
# Cell 4 — Helper utilities (manifest, save_json)
############################################
"""

def save_json(obj, path):
  with open(path,'w',encoding='utf-8') as f:
    json.dump(obj,f,ensure_ascii=False,indent=2)


def load_json(path):
  with open(path,'r',encoding='utf-8') as f:
    return json.load(f)

"""############################################
# Cell 5 — Agent/Task YAML templates (write config files)
############################################
"""



"""############################################
# Cell 6 — Data Ingest Agent (function)
############################################
"""

def data_ingest(csv_path):
  df = pd.read_csv(csv_path)
  now = datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')
  snapshot_dir = os.path.join(PROJECT_ROOT,'data','raw', now)
  os.makedirs(snapshot_dir, exist_ok=True)
  snapshot_path = os.path.join(snapshot_dir, os.path.basename(csv_path))
  df.to_csv(snapshot_path, index=False)
  manifest = {
    'source': csv_path,
    'snapshot': snapshot_path,
    'rows': int(len(df)),
    'columns': df.columns.tolist(),
    'ingested_at': now
  }
  save_json(manifest, os.path.join(snapshot_dir,'manifest.json'))
  # produce schema.json (basic types + sample values)
  schema = {
    'columns': []
  }
  for c in df.columns:
    schema['columns'].append({'name': c, 'dtype': str(df[c].dtype), 'sample_values': df[c].dropna().unique().tolist()[:5]})
  save_json(schema, os.path.join(snapshot_dir,'schema.json'))
  df.head(10).to_csv(os.path.join(snapshot_dir,'preview.csv'), index=False)
  print('Ingest done:', snapshot_path)

  return snapshot_path, schema

"""############################################
# Cell 7 — Validation Agent
############################################
"""

def validate_data(snapshot_path):
  df = pd.read_csv(snapshot_path)
  report = {'null_rates': {}, 'numeric_stats': {}, 'high_null_cols': []}
  for c in df.columns:
    report['null_rates'][c] = float(df[c].isna().mean())
    if pd.api.types.is_numeric_dtype(df[c]):
      report['numeric_stats'][c] = {
        'min': float(df[c].min(skipna=True)),
        'max': float(df[c].max(skipna=True)),
        'mean': float(df[c].mean(skipna=True)),
        'std': float(df[c].std(skipna=True))
      }
  report['high_null_cols'] = [c for c,r in report['null_rates'].items() if r>0.2]
  save_json(report, os.path.join(PROJECT_ROOT,'data','processed','qc_report.json'))
  print('Validation done')

  return report

"""############################################
# Cell 8 — Advisor Agent: design pipeline
############################################
"""

############################################
# Cell 8 — Advisor Agent: design pipeline (calls Groq LLaMA)
############################################
import requests
from dotenv import load_dotenv

# Load .env để lấy GROQ_API_KEY
load_dotenv('/content/drive/MyDrive/Colab Notebooks/MultiAgent_Loan/env/.env')
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

def generate_text(description, model="llama3-8b-8192"):
    """
    Gọi Groq API với model LLaMA để sinh text.
    """
    if not GROQ_API_KEY:
        raise ValueError("Missing GROQ_API_KEY in environment variables.")

    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are an AI financial advisor and ML pipeline architect."},
            {"role": "user", "content": description}
        ],
        "temperature": 0.2
    }

    url = "https://api.groq.com/openai/v1/chat/completions"
    resp = requests.post(url, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()
    data = resp.json()
    return data["choices"][0]["message"]["content"]

def advisor_design_pipeline(schema_path, qc_report_path, target_column_hint=None):
    """
    Advisor Agent dùng Groq LLaMA để sinh pipeline_plan.yaml dựa vào schema + qc_report.
    """
    schema = load_json(schema_path)
    qc = load_json(qc_report_path)

    desc = f"""
    Tôi có một dataset với schema sau:\n{json.dumps(schema,indent=2,ensure_ascii=False)}
    Và một báo cáo chất lượng dữ liệu (qc_report):\n{json.dumps(qc,indent=2,ensure_ascii=False)}

    Hãy đề xuất nội dung file pipeline_plan.yaml cho quy trình ML:
    - Các bước preprocess (numeric, categorical, imputation, encoding, scaling)
    - Feature engineering gợi ý
    - Chiến lược resampling (SMOTE/ADASYN/undersample)
    - Model đề xuất (ví dụ RandomForest, XGBoost) + params cơ bản
    - Có/không hyperparam_search
    - Explainability (SHAP/LIME)
    - Monitoring (PSI threshold)

    Trả về đúng định dạng YAML.
    """

    try:
        plan_text = generate_text(desc, model="llama3-8b-8192")
        plan_path = os.path.join(PROJECT_ROOT,'pipeline_plan.yaml')
        with open(plan_path,'w',encoding='utf-8') as f:
            f.write(plan_text)
        print('✅ Advisor created pipeline_plan.yaml via Groq LLaMA')
        return plan_path
    except Exception as e:
        print("⚠️ Groq API call failed, fallback to heuristic plan:", e)
        # fallback plan đơn giản
        numeric = [c['name'] for c in schema['columns'] if c['dtype'].startswith(('int','float'))]
        categorical = [c['name'] for c in schema['columns'] if c['name'] not in numeric]
        if target_column_hint and target_column_hint in numeric:
            numeric.remove(target_column_hint)
        plan = {
            'preprocess': {
                'numeric': numeric,
                'categorical': categorical,
                'imputation': 'mean',
                'encoding': 'onehot',
                'scaling': 'standard'
            },
            'feature_engineering': ['income_log','age_bucket','tenure_ratio'],
            'resample': 'SMOTE',
            'model': {'type':'RandomForestClassifier','params':{'n_estimators':200,'class_weight':'balanced'}},
            'hyperparam_search': False,
            'explainability':'SHAP',
            'monitoring': {'psi_threshold':0.15}
        }
        save_json(plan, os.path.join(PROJECT_ROOT,'pipeline_plan.json'))
        print('✅ Advisor produced heuristic pipeline_plan.json')
        return os.path.join(PROJECT_ROOT,'pipeline_plan.json')

"""############################################
# Cell 9 — Feature Engineering Agent
############################################
"""

def feature_engineer(snapshot_path, plan_path):
  df = pd.read_csv(snapshot_path)
  plan = load_json(plan_path)
  feats = {}
  # Example domain features — only create when columns exist
  if 'Income' in df.columns:
    df['income_log'] = np.log1p(df['Income'])
    feats['income_log'] = 'log(Income)'
  if 'Age' in df.columns:
    bins = [0,25,35,45,60,200]
    df['age_bucket'] = pd.cut(df['Age'], bins=bins, labels=['18-25','26-35','36-45','46-60','60+'])
    feats['age_bucket'] = 'binned Age'
  if 'CURRENT_JOB_YRS' in df.columns and 'CURRENT_HOUSE_YRS' in df.columns:
    df['tenure_ratio'] = df['CURRENT_JOB_YRS']/(df['CURRENT_HOUSE_YRS']+1)
    feats['tenure_ratio'] = 'job yrs / house yrs'
  out_csv = os.path.join(PROJECT_ROOT,'data','processed','engineered_features.csv')
  df.to_csv(out_csv, index=False)
  save_json({'features':feats}, os.path.join(PROJECT_ROOT,'data','processed','feature_metadata.json'))
  print('Feature engineering done')
  return out_csv

"""############################################
# Cell 10 — Preprocessing Agent (build pipeline from plan)
############################################
"""

def preprocess_and_split(engineered_csv, plan_path, target_column='Risk_Flag', test_size=0.2, val_size=0.1, random_state=42):
  df = pd.read_csv(engineered_csv)
  plan = load_json(plan_path)
  # identify numeric & categorical based on plan or auto
  numeric_cols = plan.get('preprocess',{}).get('numeric') or [c for c in df.select_dtypes(include=[np.number]).columns.tolist() if c!=target_column]
  cat_cols = plan.get('preprocess',{}).get('categorical') or [c for c in df.columns if c not in numeric_cols and c!=target_column]
  # basic fillna
  df[numeric_cols] = df[numeric_cols].fillna(0)
  df[cat_cols] = df[cat_cols].fillna('MISSING')
  X = df.drop(columns=[target_column])
  y = df[target_column].astype(int)
  # stratified split
  X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=test_size+val_size, stratify=y, random_state=random_state)
  val_prop = val_size/(test_size+val_size)
  X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=1-val_prop, stratify=y_temp, random_state=random_state)
  # ColumnTransformer
  num_pipeline = Pipeline([('scaler', StandardScaler())])
  cat_pipeline = Pipeline([('ohe', OneHotEncoder(handle_unknown='ignore', sparse=False))])
  preprocessor = ColumnTransformer([('num', num_pipeline, numeric_cols), ('cat', cat_pipeline, cat_cols)], remainder='drop', sparse_threshold=0)
  # fit on train
  preprocessor_fitted = preprocessor.fit(X_train)
  joblib.dump(preprocessor_fitted, os.path.join(PROJECT_ROOT,'models','preprocess_pipeline.joblib'))
  # save splits
  X_train.to_pickle(os.path.join(PROJECT_ROOT,'data','processed','X_train_raw.pkl'))
  X_val.to_pickle(os.path.join(PROJECT_ROOT,'data','processed','X_val_raw.pkl'))
  X_test.to_pickle(os.path.join(PROJECT_ROOT,'data','processed','X_test_raw.pkl'))
  y_train.to_pickle(os.path.join(PROJECT_ROOT,'data','processed','y_train.pkl'))
  y_val.to_pickle(os.path.join(PROJECT_ROOT,'data','processed','y_val.pkl'))
  y_test.to_pickle(os.path.join(PROJECT_ROOT,'data','processed','y_test.pkl'))
  print('Preprocessing & split done; preprocessor saved')

  return preprocessor_fitted, (X_train, X_val, X_test, y_train, y_val, y_test)

"""############################################
# Cell 11 — Resampling Agent
############################################
"""

def resample_train(preprocessor_fitted, X_train, y_train, method='SMOTE'):
  X_tr = preprocessor_fitted.transform(X_train)
  if method.lower() in ('smote','adasyn'):
    sm = SMOTE(random_state=42)
    X_res, y_res = sm.fit_resample(X_tr, y_train)
  else:
    X_res, y_res = X_tr, y_train.values
  np.save(os.path.join(PROJECT_ROOT,'data','processed','X_train_trans.npy'), X_res)
  np.save(os.path.join(PROJECT_ROOT,'data','processed','y_train_trans.npy'), y_res)
  save_json({'method': method, 'orig_counts': dict(pd.Series(y_train).value_counts()), 'resampled_counts': dict(pd.Series(y_res).value_counts())}, os.path.join(PROJECT_ROOT,'data','processed','resample_report.json'))
  print('Resampling done')
  return X_res, y_res

"""############################################
# Cell 12 — Hyperparam Agent (simple grid)
############################################
"""

def hyperparam_search(X_res, y_res):
  # small search for RF max_depth
  params = {'n_estimators':[100,200], 'max_depth':[None,10,20]}
  best = None
  best_score = -1
  for n in params['n_estimators']:
    for d in params['max_depth']:
      clf = RandomForestClassifier(n_estimators=n, max_depth=d, class_weight='balanced', random_state=42)
      skf = StratifiedKFold(n_splits=3)
      scores = []
      for train_idx, val_idx in skf.split(X_res, y_res):
        clf.fit(X_res[train_idx], y_res[train_idx])
        probs = clf.predict_proba(X_res[val_idx])[:,1]
        scores.append(roc_auc_score(y_res[val_idx], probs))
      mean_score = np.mean(scores)
      if mean_score>best_score:
        best_score = mean_score
        best = {'n_estimators':n, 'max_depth':d, 'score':float(mean_score)}
  save_json(best, os.path.join(PROJECT_ROOT,'models','best_params.json'))
  print('Hyperparam search done', best)

  return best

"""############################################
# Cell 13 — Training Agent
############################################
"""

def train_and_evaluate(X_res, y_res, preprocessor_fitted, X_val, y_val, best_params=None):
  clf = RandomForestClassifier(n_estimators=best_params.get('n_estimators',200), max_depth=best_params.get('max_depth',None), class_weight='balanced', random_state=42)
  clf.fit(X_res, y_res)
  joblib.dump(clf, os.path.join(PROJECT_ROOT,'models','model.joblib'))
  # eval on val
  X_val_t = preprocessor_fitted.transform(X_val)
  probs = clf.predict_proba(X_val_t)[:,1]
  preds = (probs>=0.5).astype(int)
  roc = roc_auc_score(y_val, probs)
  pr = average_precision_score(y_val, probs)
  cr = classification_report(y_val, preds, output_dict=True)
  cm = confusion_matrix(y_val, preds)
  metrics = {'roc_auc':float(roc), 'pr_auc':float(pr), 'classification_report':cr, 'confusion_matrix':cm.tolist()}
  save_json(metrics, os.path.join(PROJECT_ROOT,'models','metrics.json'))
  # save cm image
  fig,ax = plt.subplots(figsize=(4,3))
  sns.heatmap(cm,annot=True,fmt='d',ax=ax)
  fig.savefig(os.path.join(PROJECT_ROOT,'artifacts','confusion_matrix.png'))
  plt.close(fig)
  print('Training done; metrics saved')
  return clf, metrics

"""############################################
# Cell 14 — Explainability Agent (SHAP)
############################################
"""

def explainability(clf, preprocessor_fitted, X_sample):
  try:
    explainer = shap.TreeExplainer(clf)
    shap_vals = explainer.shap_values(X_sample)
    # for binary
    shap_pos = shap_vals[1]
    mean_abs = np.abs(shap_pos).mean(axis=0)

    # try to get feature names from preprocessor
    try:
      num_cols = preprocessor_fitted.transformers_[0][2]
      ohe = preprocessor_fitted.transformers_[1][1].named_steps['ohe']
      cat_cols = preprocessor_fitted.transformers_[1][2]
      cat_names = list(ohe.get_feature_names_out(cat_cols))
      feat_names = list(num_cols) + cat_names
    except Exception:
      feat_names = [f'f{i}' for i in range(mean_abs.shape[0])]
    idxs = np.argsort(-mean_abs)[:20]
    top_features = [{'feature':feat_names[i],'importance':float(mean_abs[i])} for i in idxs]
    save_json({'top_features':top_features}, os.path.join(PROJECT_ROOT,'artifacts','shap_summary.json'))

    # save summary plot
    try:
      shap.summary_plot(shap_pos, X_sample, feature_names=feat_names, show=False)
      plt.savefig(os.path.join(PROJECT_ROOT,'artifacts','shap_summary.png'), bbox_inches='tight')
      plt.close()
    except Exception:
      pass
    print('SHAP computed')
    return top_features

  except Exception as e:
    print('SHAP failed', e)
    return []

"""############################################
# Cell 15 — Market Search Agent
############################################
"""

def market_search(queries=None, output_path=os.path.join(PROJECT_ROOT,'artifacts','market_insights.json')):
  if queries is None:
    queries = ['consumer credit default trend 2025', 'interest rate outlook 2025', 'unemployment rate 2025']
  if CREWAI_AVAILABLE:
    # Use SerperDevTool via Agent
    with open(os.path.join(PROJECT_ROOT,'config','agents.yaml'),'r',encoding='utf-8') as f:
      ag = yaml.safe_load(f)
    # instantiate agent with SerperDevTool
    search_agent = Agent(config=ag['market_search_agent'], tools=[SerperDevTool(), ScrapeWebsiteTool()])
    findings = []
    for q in queries:
      # expected interface: Task driven or tool.run — adapt to your crewai_tools version
      res = search_agent.run({'query':q, 'top_n':5}) if hasattr(search_agent,'run') else search_agent.simple_run({'query':q})
      findings.append({'query':q,'result':res})
    save_json({'generated_at':datetime.utcnow().isoformat(),'findings':findings}, output_path)
    print('Market search (CrewAI) done')
    return output_path

  # Fallback: naive scraping
  import requests
  from bs4 import BeautifulSoup
  findings = []
  headers = {'User-Agent':'Mozilla/5.0'}
  from urllib.parse import quote_plus
  for q in queries:
    url = f'https://www.bing.com/search?q={quote_plus(q)}'
    try:
      r = requests.get(url, headers=headers, timeout=10)
      soup = BeautifulSoup(r.text, 'html.parser')
      for li in soup.select('li.b_algo')[:5]:
        a = li.find('a')
        title = a.get_text(strip=True) if a else ''
        href = a['href'] if a else ''
        p = li.find('p')
        snippet = p.get_text(strip=True) if p else ''
        findings.append({'query':q,'title':title,'url':href,'snippet':snippet})
    except Exception as e:
      print('search err', e)
  save_json({'generated_at':datetime.utcnow().isoformat(),'findings':findings}, output_path)
  print('Market search (local) done')
  return output_path

"""############################################
# Cell 16 — Decision Agent (basic rule engine)
############################################
"""

def decision_policy_apply(clf, preprocessor_fitted, X_sample_df, config=None):
  # config can contain threshold, rules
  thresh = 0.5 if not config else config.get('threshold',0.5)
  X_t = preprocessor_fitted.transform(X_sample_df)
  probs = clf.predict_proba(X_t)[:,1]
  decisions = []
  for i,p in enumerate(probs):
    dec = 'APPROVE' if p<thresh else ('MANUAL_REVIEW' if p<thresh+0.15 else 'REJECT')
    decisions.append({'index': i, 'score': float(p), 'decision': dec})
  save_json({'decisions':decisions}, os.path.join(PROJECT_ROOT,'artifacts','decision_report.json'))
  print('Decision policy applied')
  return decisions

"""############################################
# Cell 17 — Monitoring Agent (PSI)
############################################
"""

def population_stability_index(expected, actual, buckets=10):
  # simple PSI for numeric arrays
  expected_perc, bins = np.histogram(expected, bins=buckets)
  actual_perc, _ = np.histogram(actual, bins=bins)
  expected_perc = expected_perc / expected_perc.sum()
  actual_perc = actual_perc / actual_perc.sum()
  psi = np.sum((expected_perc - actual_perc) * np.log((expected_perc + 1e-8)/(actual_perc + 1e-8)))
  return psi

def monitor_model_baseline(feature_name, baseline_vals, recent_vals, threshold=0.1):
  psi = population_stability_index(np.array(baseline_vals), np.array(recent_vals))
  report = {'feature':feature_name, 'psi': float(psi), 'drift': psi>threshold}
  save_json(report, os.path.join(PROJECT_ROOT,'artifacts','monitor_report.json'))
  if psi>threshold:
    save_json({'drift_flag': True, 'reason': f'psi_{feature_name} > {threshold}'}, os.path.join(PROJECT_ROOT,'artifacts','drift_flag.json'))
  print('Monitoring done', report)
  return report

"""############################################
# Cell 18 — Reporting Agent (assemble final report using advisor review)
############################################
"""

def assemble_final_report(metrics_path=os.path.join(PROJECT_ROOT,'models','metrics.json'),
                            shap_path=os.path.join(PROJECT_ROOT,'artifacts','shap_summary.json'),
                            market_path=os.path.join(PROJECT_ROOT,'artifacts','market_insights.json'),
                            advisor_review_path=os.path.join(PROJECT_ROOT,'artifacts','advisor_review.txt'),
                            out_html=os.path.join(PROJECT_ROOT,'reports','report.html'),
                            out_pdf=os.path.join(PROJECT_ROOT,'reports','report.pdf')):
  metrics = load_json(metrics_path) if os.path.exists(metrics_path) else {}
  shap_s = load_json(shap_path) if os.path.exists(shap_path) else {}
  market = load_json(market_path) if os.path.exists(market_path) else {}
  advisor_review = ''
  if os.path.exists(advisor_review_path):
    with open(advisor_review_path,'r',encoding='utf-8') as f:
      advisor_review = f.read()
  tpl = '''<!doctype html><html><head><meta charset="utf-8"><title>Loan Risk Report</title></head><body> <h1>Loan Risk Report</h1> <h2>Executive summary</h2> <p>{{exec_summary}}</p> <h2>Metrics</h2> <pre>{{metrics}}</pre> <h2>SHAP top features</h2> <pre>{{shap}}</pre> <h2>Market insights (sample)</h2> <pre>{{market_findings}}</pre> <h2>Advisor review</h2> <pre>{{advisor}}</pre> </body></html>'''
  env = Environment()
  template = env.from_string(tpl)
  exec_summary = f"ROC AUC: {metrics.get('roc_auc')}, PR AUC: {metrics.get('pr_auc')}"
  html = template.render(exec_summary=exec_summary, metrics=json.dumps(metrics,indent=2,ensure_ascii=False), shap=json.dumps(shap_s,indent=2,ensure_ascii=False), market_findings=json.dumps(market,indent=2,ensure_ascii=False), advisor=advisor_review)
  with open(out_html,'w',encoding='utf-8') as f:
    f.write(html)
  print('Report written', out_html)
  # optional PDF export
  try:
    from weasyprint import HTML
    HTML(out_html).write_pdf(out_pdf)
    print('PDF written', out_pdf)
  except Exception as e:
    print('PDF export skipped', e)

  return out_html

"""############################################
# Cell 19 — Advisor review (write advisor_review.txt)
############################################
"""

def advisor_review_generate(artifacts_paths):
  # artifacts_paths: dict of artifact file paths
  # If CrewAI available, delegate to advisor Agent; else use heuristic template
  if CREWAI_AVAILABLE:
    with open(os.path.join(PROJECT_ROOT,'config','agents.yaml'),'r',encoding='utf-8') as f:
      ag = yaml.safe_load(f)
    adv = Agent(config=ag['advisor_agent'])
    payload = {'task':'review_and_report','artifacts':artifacts_paths}
    res = adv.run(payload) if hasattr(adv,'run') else adv.simple_run(payload)
    review_text = res.get('text') if isinstance(res,dict) else str(res)
    with open(os.path.join(PROJECT_ROOT,'artifacts','advisor_review.txt'),'w',encoding='utf-8') as f:
      f.write(review_text)
    print('Advisor review generated via CrewAI')
    return os.path.join(PROJECT_ROOT,'artifacts','advisor_review.txt')

    # fallback heuristic text
    txt = 'Advisor summary (auto-generated):\n'
    if os.path.exists(artifacts_paths.get('models/metrics.json','')):
      m = load_json(artifacts_paths.get('models/metrics.json'))
      txt += f"Model ROC AUC: {m.get('roc_auc')}\n"
      txt += '\nSuggested next steps:\n - Validate data quality; - Monitor drift; - Review SHAP top features.'
    with open(os.path.join(PROJECT_ROOT,'artifacts','advisor_review.txt'),'w',encoding='utf-8') as f:
      f.write(txt)
    print('Advisor review (heuristic) written')
    return os.path.join(PROJECT_ROOT,'artifacts','advisor_review.txt')

"""############################################
# Cell 20 — Orchestrator: run full dynamic flow (example)
############################################
"""

def run_full_dynamic_pipeline(csv_path, target_column='Risk_Flag'):
  # 1) ingest
  snapshot_path, schema = data_ingest(csv_path)
  schema_path = snapshot_path.replace(os.path.basename(snapshot_path),'schema.json') if os.path.exists(os.path.join(os.path.dirname(snapshot_path),'schema.json')) else None
  # 2) validate
  qc = validate_data(snapshot_path)
  qc_path = os.path.join(PROJECT_ROOT,'data','processed','qc_report.json')
  # 3) advisor design pipeline
  plan_path = advisor_design_pipeline(schema_path if schema_path else os.path.join(os.path.dirname(snapshot_path),'schema.json'), qc_path, target_column_hint=target_column)
  # 4) feature engineering
  engineered_csv = feature_engineer(snapshot_path, plan_path)
  # 5) preprocess
  preproc, splits = preprocess_and_split(engineered_csv, plan_path, target_column)
  X_train, X_val, X_test, y_train, y_val, y_test = splits
  # 6) resample
  X_res, y_res = resample_train(preproc, X_train, y_train, method='SMOTE')
  # 7) hyperparam
  best = hyperparam_search(X_res, y_res)
  # 8) train
  clf, metrics = train_and_evaluate(X_res, y_res, preproc, X_val, y_val, best_params=best)
  # 9) explain
  X_sample = preproc.transform(X_val)[:200]
  explainability(clf, preproc, X_sample)
  # 10) market search
  market_search()
  # 11) decision policy on test
  decision_policy_apply(clf, preproc, X_test)
  # 12) monitoring baseline (example using Income feature)
  if 'Income' in pd.read_csv(snapshot_path).columns:
    baseline = pd.read_csv(snapshot_path)['Income'].dropna().values
    recent = baseline # demo
    monitor_model_baseline('Income', baseline, recent, threshold=0.1)
  # 13) advisor review
  artifacts = {
    'qc': os.path.join(PROJECT_ROOT,'data','processed','qc_report.json'),
    'features': os.path.join(PROJECT_ROOT,'data','processed','feature_metadata.json'),
    'metrics': os.path.join(PROJECT_ROOT,'models','metrics.json'),
    'shap': os.path.join(PROJECT_ROOT,'artifacts','shap_summary.json'),
    'decision': os.path.join(PROJECT_ROOT,'artifacts','decision_report.json'),
    'monitor': os.path.join(PROJECT_ROOT,'artifacts','monitor_report.json'),
    'market': os.path.join(PROJECT_ROOT,'artifacts','market_insights.json')
  }
  advisor_review_generate(artifacts)
  # 14) assemble final report
  assemble_final_report()
  print('Full dynamic pipeline finished. Check reports/')

run_full_dynamic_pipeline('/content/drive/MyDrive/Colab Notebooks/MultiAgent_Loan/data/Training Data.csv', target_column='Risk_Flag')